{
 "title": "Host",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime ubuntu",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "custom_node_uptime_seconds" }
   ]
  },
  {
   "title": "Ubuntu Battery ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laptop_battery_capacity_percent"
    }
   ]
  },
  {
   "title": "Ubuntu Cpu Temp",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ram_used_bytes" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Ubuntu voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "battery_voltage_volt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Status ubuntu",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "battery0_status", "legendFormat": "__auto" },
    { "expr": "battery1_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ubuntu Cpu busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[30s])) * 100)\n"
    }
   ]
  },
  {
   "title": "Ubuntu Fan speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_thinkpad_hwmon\",sensor=\"fan1\"} "
    }
   ]
  },
  {
   "title": "Dns To 8.8.8.8 Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_google_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU time usage split by state, normalized across all CPU cores",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_guest_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))) > 0",
     "legendFormat": "Guest CPU usage"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"lo\"}[30s])\n+\nrate(node_network_transmit_bytes_total{device=\"lo\"}[30s])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}